version: 2.1
jobs:
  initializeCode:
    docker:
        - image: alpine:3.7
    steps:
      - checkout
  runmake-1:
    working_directory: makeme
    docker:
        - image: ubuntu
    steps:
      - checkout
      - run:
          name: "install make"
          command: |
            apt-get update
            apt-get install make -y
      - run:
          name: "run make"
          command: |
             cd makeme
             make one
  runmake-2:
    working_directory: makeme
    docker:
        - image: ubuntu
    steps:
      - checkout
      - run:
          name: "install make"
          command: |
            apt-get update
            apt-get install make -y
      - run:
          name: "run make"
          command: |
            cd makeme
            pwd
            ls
            make two
  runmake-3:
    working_directory: makeme
    docker:
        - image: ubuntu
    steps:
      - checkout
      - run:
          name: "install make"
          command: |
            at-get update
            at-get install make -y
      - run:
          name: "run make"
          when: always
          command: |
            cd makeme
            pwd
            ls
            make three
      - run:
          name: "Cleaning"
          when: always
          command: echo "cleaning stuff"


workflows:
  paralellWorkflow:
    jobs:
      - initializeCode
      - runmake-1
      - runmake-2
      - runmake-3
