version: 2.1
jobs:
  initializeCode:
    docker:
        - image: alpine:3.7
    steps:
      - checkout
  runmake:
    docker:
        - image: ubuntu
    steps:
      - checkout
      - run:
          name: "install make"
          command: |
            apt-get update
            apt-get install make -y
      - run:
          name: "run make"
          command: |
            cd makeme
            make
workflows:
  paralellWorkflow:
    jobs:
      - initializeCode
      - runmake:
           requires:
              - initializeCode
