version: 2.1
jobs:
  initializeCode:
    docker:
        - image: alpine:3.7
    steps:
      - checkout
  runmake:
    docker:
        - image: alpine:3.7
    steps:
      - run:
          name: "run make"
          command: |
            cd makeme
            make
workflows:
  paralellWorkflow:
    jobs:
      - initializeCode
      - runmake
